version: 2
updates:

  # Docker base image updates
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: monthly
      time: "11:00"
    open-pull-requests-limit: 25

  # Python (pip) dependencies
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
      time: "11:00"
    open-pull-requests-limit: 25

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: monthly
      time: "11:00"
    open-pull-requests-limit: 25
