#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook running"
echo "IMAGE_NAME = ${IMAGE_NAME}"
echo "DOCKER_REPO = ${DOCKER_REPO}"
echo "CACHE_TAG = ${CACHE_TAG}"
export BRANCH=${TRAVIS_BRANCH:-`git symbolic-ref --short HEAD`}
if [ "$BRANCH" == "master" -o "$BRANCH" == "mini" ]; then
    export STAGE1TAG="latest"
else
    export STAGE1TAG="${BRANCH}"
fi

export DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
export COMMIT=${TRAVIS_COMMIT:-`git rev-parse --short HEAD`}
docker build --build-arg BUILD_DATE=$DATE \
             --build-arg VCS_REF=$COMMIT \
             --build-arg BRANCH=$BRANCH \
             --build-arg STAGE1TAG=$STAGE1TAG \
             -t ${IMAGE_NAME} . && \
echo "Built and tagged ${IMAGE_NAME}"
